# Site settings
title: Jekyll-Edu Blog
description: 'Fork, responsive theme for Jekyll'
url: 'http://IBM-SkillBuild.github.io'
baseurl: '/'


author:
  name: 'Eduardo Cabrera'
  email: ecabrerablazquez@gmail.com
  twitter_username: CabreraBlazquez
  linkedin_username: e-cabrera-blazquez
  
future: true
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
